# Common properties shared across all environments
api:
  name: "${project.artifactId}"
  version: "${project.version}"
  
# Common properties that can be overridden by applications
common:
  errors:
    error-code-400: "BAD_REQUEST"
    error-code-404: "NOT_FOUND"
    error-code-405: "METHOD_NOT_ALLOWED"
    error-code-406: "NOT_ACCEPTABLE"
    error-code-415: "UNSUPPORTED_MEDIA_TYPE"
    error-code-500: "INTERNAL_SERVER_ERROR"
    error-code-501: "NOT_IMPLEMENTED"
