# Use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.

target-api:
  client-id: "Plain Text User"
  client-secret: "![Blowfish encrypted password]"
